name: "UniFi Captive Portal"
description: "A custom add-on for Home Assistant to provide a captive portal for UniFi WiFi networks."
version: "1.0.0"
slug: "unifi-portal"
arch:
  - armv7
  - arm64
  - amd64
  - i386
startup: "application"
boot: "auto"
ports:
  80/tcp: 80